In [8]:
import numpy as np

print("x")
x = np.array([[1], [2]])  # a vector of length n
print(x)
print("M")
M = np.array([[4, 5], [6, 7], [8, 9]])  # a matrix of size (m,n)
print(M)
print("y")
print(M@x)

# Compute the outer product of x and a vector of ones of length m
outer_product = np.outer(x, np.ones(M.shape[0]))

# Print the result
print("grad")
print(outer_product)


x
[[1]
 [2]]
M
[[4 5]
 [6 7]
 [8 9]]
y
[[14]
 [20]
 [26]]
grad
[[1. 1. 1.]
 [2. 2. 2.]]


In [29]:
import numpy as np
def gaussian_pdf(x, mu, sigma):
    return  1/np.sqrt(2*np.pi*sigma**2)*np.exp(-0.5*(x-mu)**2)
def multi_gaussian_pdf(x, mu, sigma):
    sigma_inv = np.linalg.inv(sigma)
    det_sigma = np.linalg.det(sigma)
    dim = x.shape[0]
    print("dim is")
    print(dim)
    print("det is")
    print(det_sigma)
    print("quad")
    return 1/np.sqrt( ( (2*np.pi)**dim )*det_sigma )*np.exp( -0.5*(x-mu).T@sigma_inv@(x-mu) )




def multivariate_gaussian_pdf(x, mu, cov):
    """
    This function returns the multivariate Gaussian probability density function (PDF)
    for a given vector x with mean vector mu and covariance matrix cov.

    :param x: (numpy.ndarray) The vector at which to evaluate the PDF.
    :param mu: (numpy.ndarray) The mean vector of the distribution.
    :param cov: (numpy.ndarray) The covariance matrix of the distribution.
    :return: (float) The probability density function evaluated at x.
    """
    k = len(mu)  # The dimension of the distribution
    det = np.linalg.det(cov)  # The determinant of the covariance matrix
    inv = np.linalg.inv(cov)  # The inverse of the covariance matrix
    exp = np.exp(-0.5 * np.dot(np.dot((x - mu).T, inv), (x - mu)))  # The exponential term of the PDF
    coeff = 1.0 / ((2 * np.pi)**(k/2) * det**0.5)  # The coefficient term of the PDF
    return coeff * exp

    
x = np.array([1/np.sqrt(np.pi), 2])
mu = np.array([0, 2])
cov = np.diag( np.array([1/np.sqrt(2*np.pi), (1/np.sqrt(2*np.pi))]) )
print(np.log(multi_gaussian_pdf(x, mu, sigma)))
pdf = multivariate_gaussian_pdf(x, mu, cov)
print(np.log(pdf))

def function(x, sigma, mu, d):
    a = 2*np.pi*sigma**2
    a2 = 1/a**(d/2)
    b1 = np.linalg.norm(x-mu)**2
    b2 = -1/(2*sigma**2)
    return a2*np.exp(b2*b1)
print(np.log(function(x, sigma[0,0], mu, 2)))
    
    


dim is
2
det is
0.15915494309189535
quad
-1.317880813606105
-1.3178808136061053
-0.9999999999999998
